ERROR - 2025-10-24 13:08:02 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'lms_fundar' in D:\XAMPP\htdocs\ITE311-Fundar\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'lms_fundar', 3306, '', 0)
#1 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\XAMPP\htdocs\ITE311-Fundar\app\Controllers\Auth.php(203): CodeIgniter\Database\BaseBuilder->get()
#5 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#6 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\XAMPP\htdocs\ITE311-Fundar\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 D:\XAMPP\htdocs\ITE311-Fundar\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\XAMPP\htdocs\ITE311-Fundar\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'lms_fundar' in D:\XAMPP\htdocs\ITE311-Fundar\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseConnection.php(419): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\XAMPP\htdocs\ITE311-Fundar\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\XAMPP\htdocs\ITE311-Fundar\app\Controllers\Auth.php(203): CodeIgniter\Database\BaseBuilder->get()
#4 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(933): App\Controllers\Auth->login()
#5 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 D:\XAMPP\htdocs\ITE311-Fundar\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\XAMPP\htdocs\ITE311-Fundar\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#8 D:\XAMPP\htdocs\ITE311-Fundar\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 D:\XAMPP\htdocs\ITE311-Fundar\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
CRITICAL - 2025-10-24 13:08:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'lms_fundar'
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 465.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE   (
`email` = :email:
OR `name` = :name:
 )
 LIMIT 1', [...], false)
 3 APPPATH\Controllers\Auth.php(203): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
